### ISSUE TITLE
JQuery not loaded correctly

### ISSUE THREAD

**Issue by emerald000** [L0gi/nicerFutureSite#3]
I get an error message in the browser console of Firefox 48.0.2 after installing in GreaseMonkey: "$ is not defined" at "waitForKeyElements.js:37:9".

Looks like JQuery is not loaded correctly.

Symptoms include correct styling, but no auto-reload.

**Comment by L0gi** [comment]
thanks for noticing, apperently there is a bug on chrome with sandboxing of scripts, allowing the userscript to see the original sites jquery and not needign an seperate @require for it. This bug is not present in firefox.

the problem should be fixed now
